# Generated by Django 4.1.7 on 2023-04-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="user",
        ),
    ]
